export CUDA_VISIBLE_DEVICES=2,3
python -m torch.distributed.run --nproc_per_node=1 --master_port=3005 main.py \
--data_dir=/data2/tanglv/xhk/ASAM/2023-9-7/Ad-Sam-Main/sam_continue_learning/easyrobust/benchmarks/data/imagenet1k-subset \
--model resnet50 \
--amp \
--epochs=5 \
--batch-size=128 \
--lr=0.001 \
--drop-path=0.25 \
--model-ema \
--model-ema-decay=0.99992 \
--opt=adamw \
--opt-eps=1e-8 \
--weight-decay=0.05 \
--sched=cosine \
--warmup-lr=1e-6 \
--warmup-epochs=5 \
--cooldown-epochs=10 \
--patience-epochs=10 \
--color-jitter=0.4 \
--aa=rand-m9-mstd0.5-inc1 \
--smoothing=0.1 \
--reprob=0.25 \
--mixup=0.8 \
--cutmix=1.0 \
--pin-mem \
--mean 0.0 0.0 0.0 \
--std 1.0 1.0 1.0 \
--output=output/dat \
--experiment=tmp \
--pretrained 